# Generated by Django 5.0.1 on 2024-02-12 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_materials'),
        ('materials', '0005_alter_materials_course'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_pay', models.DateField(verbose_name='дата оплаты')),
                ('method_pay', models.CharField(choices=[('cash', 'наличными'), ('card', 'картой')], max_length=15, verbose_name='метод оплаты')),
                ('money', models.IntegerField(verbose_name='сумма оплаты')),
                ('courses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='курсы')),
                ('materials', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materials', verbose_name='уроки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
