# Generated by Django 5.0.1 on 2024-02-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='телефон'),
        ),
    ]
