# Generated by Django 5.0.2 on 2024-03-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_client_options_client_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='payment_id',
        ),
    ]
