# Generated by Django 5.0.2 on 2024-03-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_payment_course_alter_payment_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='day_pay',
            field=models.DateField(blank=True, null=True, verbose_name='дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method_pay',
            field=models.CharField(blank=True, choices=[('cash', 'наличными'), ('card', 'картой')], max_length=15, null=True, verbose_name='метод оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='money',
            field=models.IntegerField(blank=True, null=True, verbose_name='сумма оплаты'),
        ),
    ]
