# Generated by Django 5.0.2 on 2024-03-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_payment_day_pay_alter_payment_method_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method_pay',
            field=models.TextField(blank=True, choices=[('cash', 'наличными'), ('card', 'картой')], null=True, verbose_name='метод оплаты'),
        ),
    ]
